// <auto-generated />
namespace JewelryGolden.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update));
        
        string IMigrationMetadata.Id
        {
            get { return "202510251018131_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
